// 安睡记/src/pages/Login.tsx
import { useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Moon, Phone, ShieldCheck, Eye, EyeOff, Sparkles } from 'lucide-react';
import { useStore } from '@/store';

export default function Login() {
  const [phone, setPhone] = useState('');
  const [code, setCode] = useState('');
  const [countdown, setCountdown] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [showCode, setShowCode] = useState(false);
  
  const login = useStore(state => state.login);
  const navigate = useNavigate();

  const handleSendCode = useCallback(() => {
    if (!/^1\d{10}$/.test(phone)) {
      setError('请输入正确的手机号');
      return;
    }
    setError('');
    setCountdown(60);
    const timer = setInterval(() => {
      setCountdown(prev => {
        if (prev <= 1) {
          clearInterval(timer);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
  }, [phone]);

  const handleLogin = useCallback(async () => {
    if (!/^1\d{10}$/.test(phone)) {
      setError('请输入正确的手机号');
      return;
    }
    if (code.length !== 6) {
      setError('请输入6位验证码');
      return;
    }
    if (code !== '123456') {
      setError('验证码错误，测试验证码为：123456');
      return;
    }
    
    setLoading(true);
    setError('');
    try {
      const success = await login(phone, code);
      if (success) {
        navigate('/', { replace: true });
      } else {
        setError('登录失败，请重试');
      }
    } catch (e) {
      setError('登录失败，请重试');
    } finally {
      setLoading(false);
    }
  }, [phone, code, login, navigate]);

  const handleQuickLogin = useCallback(() => {
    setPhone('13800138000');
    setCode('123456');
    setError('');
  }, []);

  return (
    <div className="min-h-full bg-gradient-to-b from-sleep-dark via-sleep-deep to-sleep-medium flex flex-col relative overflow-hidden">
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-10 left-10 w-64 h-64 bg-primary-500/10 rounded-full blur-3xl" />
        <div className="absolute bottom-32 right-5 w-48 h-48 bg-purple-500/10 rounded-full blur-3xl" />
        <div className="absolute top-1/3 right-10 w-32 h-32 bg-blue-400/10 rounded-full blur-2xl" />
      </div>
      
      <div className="flex-1 flex flex-col items-center justify-center px-8 py-12 relative z-10">
        <div className="mb-12 text-center animate-fade-in-up">
          <div className="w-24 h-24 bg-gradient-to-br from-white/10 to-white/5 rounded-3xl flex items-center justify-center mx-auto mb-6 backdrop-blur-soft border border-white/10 shadow-2xl">
            <Moon size={44} className="text-white" fill="white" fillOpacity={0.2} />
          </div>
          <h1 className="text-4xl font-bold text-white mb-3 tracking-tight">安睡记</h1>
          <p className="text-white/50 text-base">记录每一夜好眠，拥抱美好生活</p>
        </div>

        <div className="w-full max-w-sm space-y-5">
          <div className="card-glass p-6 space-y-5 animate-fade-in-up" style={{ animationDelay: '0.1s' }}>
            <div className="space-y-2.5">
              <label className="text-white/70 text-sm font-medium ml-1">手机号</label>
              <div className="input-field">
                <Phone size={19} className="input-icon" />
                <input
                  type="tel"
                  placeholder="请输入手机号"
                  value={phone}
                  onChange={(e) => {
                    setPhone(e.target.value.replace(/\D/g, '').slice(0, 11));
                    setError('');
                  }}
                  className="input-text"
                  maxLength={11}
                />
              </div>
            </div>

            <div className="space-y-2.5">
              <label className="text-white/70 text-sm font-medium ml-1">验证码</label>
              <div className="flex items-center gap-3 min-w-0">
                <div className="flex-1 input-field min-w-0">
                  <ShieldCheck size={19} className="input-icon" />
                  <input
                    type={showCode ? 'text' : 'password'}
                    placeholder="请输入6位验证码"
                    value={code}
                    onChange={(e) => {
                      setCode(e.target.value.replace(/\D/g, '').slice(0, 6));
                      setError('');
                    }}
                    className="input-text tracking-widest min-w-0"
                    maxLength={6}
                  />
                  <button
                    type="button"
                    onClick={() => setShowCode(!showCode)}
                    className="text-white/40 hover:text-white/70 transition-colors ml-2 p-1 flex-shrink-0"
                  >
                    {showCode ? <EyeOff size={18} /> : <Eye size={18} />}
                  </button>
                </div>
                <button
                  type="button"
                  onClick={handleSendCode}
                  disabled={countdown > 0}
                  className={`btn-small whitespace-nowrap flex-shrink-0 w-28 ${
                    countdown > 0
                      ? 'bg-white/[0.04] text-white/40 cursor-not-allowed border border-white/[0.06]'
                      : 'bg-primary-500/20 text-primary-400 hover:bg-primary-500/30 border border-primary-500/30'
                  }`}
                >
                  {countdown > 0 ? `${countdown}s` : '获取验证码'}
                </button>
              </div>
            </div>

            {error && (
              <div className="bg-red-500/10 border border-red-500/20 rounded-xl py-2.5 px-4">
                <p className="text-red-400 text-sm text-center">{error}</p>
              </div>
            )}

            <button
              onClick={handleLogin}
              disabled={loading}
              className="w-full btn-primary disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  登录中...
                </span>
              ) : '登录'}
            </button>
          </div>

          <p className="text-center text-white/30 text-xs animate-fade-in" style={{ animationDelay: '0.2s' }}>
            登录即表示同意 <span className="text-primary-400/80">用户协议</span> 和 <span className="text-primary-400/80">隐私政策</span>
          </p>
          
          <button
            type="button"
            onClick={handleQuickLogin}
            className="w-full card-soft p-5 hover:bg-white/[0.06] transition-all duration-300 cursor-pointer group animate-fade-in-up"
            style={{ animationDelay: '0.25s' }}
          >
            <div className="flex items-center justify-center gap-2 mb-1.5">
              <Sparkles size={16} className="text-primary-400" />
              <p className="text-white/80 text-sm font-medium group-hover:text-white transition-colors">
                点击使用测试账号
              </p>
            </div>
            <p className="text-white/40 text-xs text-center">
              手机号：<span className="text-white/60 font-mono">13800138000</span> · 验证码：<span className="text-primary-400 font-mono">123456</span>
            </p>
          </button>
        </div>
      </div>
    </div>
  );
}

// 小芽成长录/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-wrapper">
      <div class="login-header">
        <div class="logo">🌱</div>
        <h1>小芽成长录</h1>
        <p>记录宝宝每一刻的成长</p>
      </div>

      <div class="login-form">
        <div class="form-card">
          <van-cell-group>
            <van-field
              v-model="phone"
              type="tel"
              placeholder="请输入手机号"
              maxlength="11"
              clearable
            >
              <template #left-icon>
                <span class="field-icon">📱</span>
              </template>
            </van-field>
            <van-field
              v-model="code"
              type="number"
              placeholder="请输入验证码"
              maxlength="6"
              clearable
            >
              <template #left-icon>
                <span class="field-icon">🔐</span>
              </template>
              <template #button>
                <van-button
                  size="small"
                  type="primary"
                  :disabled="countdown > 0"
                  @click="sendCode"
                  class="code-btn"
                >
                  {{ countdown > 0 ? `${countdown}s` : '获取验证码' }}
                </van-button>
              </template>
            </van-field>
          </van-cell-group>

          <van-button
            type="primary"
            round
            block
            class="login-btn"
            :disabled="!phone || !code"
            @click="handleLogin"
          >
            登 录
          </van-button>

          <div class="test-account">
            <p class="test-title">测试账号</p>
            <div class="test-item" @click="fillTestAccount('13800138000', '123456')">
              <span class="test-phone">13800138000</span>
              <span class="test-code">验证码: 123456</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useUserStore } from '@/stores/user'
import { showToast } from 'vant'

const router = useRouter()
const userStore = useUserStore()

const phone = ref('')
const code = ref('')
const countdown = ref(0)

const sendCode = () => {
  if (!phone.value || phone.value.length !== 11) {
    showToast('请输入正确的手机号')
    return
  }
  
  showToast('验证码已发送: 123456')
  countdown.value = 60
  const timer = setInterval(() => {
    countdown.value--
    if (countdown.value <= 0) {
      clearInterval(timer)
    }
  }, 1000)
}

const handleLogin = () => {
  if (!phone.value || phone.value.length !== 11) {
    showToast('请输入正确的手机号')
    return
  }
  if (!code.value || code.value.length !== 6) {
    showToast('请输入正确的验证码')
    return
  }
  
  userStore.login(phone.value)
  showToast('登录成功')
  router.push('/home')
}

const fillTestAccount = (phoneNum, testCode) => {
  phone.value = phoneNum
  code.value = testCode
}
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  padding: 20px;
  box-sizing: border-box;
}

.login-wrapper {
  max-width: 420px;
  margin: 0 auto;
  padding-top: 40px;
}

.login-header {
  text-align: center;
  margin-bottom: 40px;
  color: white;
}

.logo {
  font-size: 70px;
  margin-bottom: 15px;
}

.login-header h1 {
  font-size: 28px;
  margin-bottom: 8px;
  font-weight: 600;
}

.login-header p {
  font-size: 15px;
  opacity: 0.9;
}

.login-form {
  width: 100%;
}

.form-card {
  background: white;
  border-radius: 20px;
  padding: 30px 20px;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.15);
}

.field-icon {
  font-size: 18px;
  margin-right: 5px;
}

.code-btn {
  min-width: 100px;
}

.login-btn {
  margin-top: 30px;
  height: 50px;
  font-size: 17px;
  font-weight: 500;
}

.test-account {
  margin-top: 30px;
  padding-top: 20px;
  border-top: 1px dashed #e0e0e0;
}

.test-title {
  font-size: 14px;
  color: #999;
  margin-bottom: 12px;
  text-align: center;
}

.test-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  background: linear-gradient(135deg, #ffeaa7 0%, #fdcb6e 100%);
  border-radius: 12px;
  cursor: pointer;
  transition: transform 0.2s;
}

.test-item:active {
  transform: scale(0.98);
}

.test-phone {
  font-size: 15px;
  color: #333;
  font-weight: 600;
}

.test-code {
  font-size: 13px;
  color: #666;
}

:deep(.van-field__control) {
  font-size: 16px;
}

:deep(.van-cell-group) {
  border-radius: 12px;
  overflow: hidden;
}
</style>
